server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60
  profiles:
    active: local
  jackson:
    default-property-inclusion: NON_EMPTY
  devtools:
    livereload:
      enabled: false
  datasource:
    url: jdbc:h2:mem:vel-ops-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, shutdown, loggers
  endpoint:
    loggers:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
      enabled: true
