### List All
GET http://{{host}}:{{port}}/{{context}}/v1/registers
Accept: application/json
Content-Type: application/json

### Register Car
POST http://{{host}}:{{port}}/{{context}}/v1/registers/car
Accept: application/json
Content-Type: application/json

{
    "carId" : 1
}

### Register Client
POST http://{{host}}:{{port}}/{{context}}/v1/registers/client
Accept: application/json
Content-Type: application/json

{
    "clientId" : 2
}
